development:
  adapter: sqlite3
  database: SitePoint-Mailboxer_development
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: SitePoint-Mailboxer_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: SitePoint-Mailboxer_production
  pool: 5
  timeout: 5000